

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


import com.app.config.koneksi;
import com.app.main.FormMenuUtama;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.util.UIScale;
import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Insets;
import java.awt.LayoutManager;
import java.sql.Connection;
import javax.swing.JFrame;
import javax.swing.JPasswordField;

/**
 *
 * @author LENOVO
 */
public class FormLogin extends javax.swing.JPanel {
    
      public final Connection conn =  koneksi.getKoneksi();

    /**
     * Creates new form login
     */
    public FormLogin() {
        initComponents();
        setLayoutForm();
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLogin = new javax.swing.JPanel();
        lb_logo = new javax.swing.JLabel();
        lb_user = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lb_pass = new javax.swing.JLabel();
        txt_pass = new javax.swing.JPasswordField();
        btn_login = new javax.swing.JButton();
        lb_title = new javax.swing.JLabel();
        btn_register = new javax.swing.JButton();

        lb_logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/icon/Group 5.png"))); // NOI18N

        lb_user.setText("Username");

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        lb_pass.setText("Password");

        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        lb_title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_title.setText("Login");

        btn_register.setText("jButton1");

        javax.swing.GroupLayout pnLoginLayout = new javax.swing.GroupLayout(pnLogin);
        pnLogin.setLayout(pnLoginLayout);
        pnLoginLayout.setHorizontalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnLoginLayout.createSequentialGroup()
                        .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnLoginLayout.createSequentialGroup()
                                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lb_user)
                                    .addComponent(lb_pass)
                                    .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 102, Short.MAX_VALUE))
                            .addComponent(lb_logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_login)
                .addGap(5, 5, 5)
                .addComponent(btn_register)
                .addContainerGap())
        );
        pnLoginLayout.setVerticalGroup(
            pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLoginLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lb_logo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_title)
                .addGap(12, 12, 12)
                .addComponent(lb_user)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lb_pass)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(pnLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_login)
                    .addComponent(btn_register))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(pnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(pnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        FormMenuUtama.Login();
    }//GEN-LAST:event_btn_loginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_login;
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lb_logo;
    private javax.swing.JLabel lb_pass;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_user;
    private javax.swing.JPanel pnLogin;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

 private void setLayoutForm() {
    setLayout(new FormLoginLayout());
    pnLogin.setLayout(new LoginLayout());
    
    lb_title.putClientProperty(FlatClientProperties.STYLE, "font:h1.font");
    pnLogin.putClientProperty(FlatClientProperties.STYLE, ""
            + "background:$Login.background;"
            + "arc:20;"
            + "border:30,40,50,30;");
    
    // Style untuk TextField dan PasswordField
    txt_username.putClientProperty(FlatClientProperties.STYLE, "arc:20;");
    txt_pass.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:20;"
        + "showRevealButton:true;"
        + "showCapsLock:true;");
        
    // Tambahkan placeholder secara terpisah
    txt_username.putClientProperty("JTextField.placeholderText", "Masukkan username Anda");
    txt_pass.putClientProperty("JTextField.placeholderText", "Masukkan password Anda");
}



    
    private class FormLoginLayout implements LayoutManager {

        @Override
        public void addLayoutComponent(String name, Component comp) {
          
        }

        @Override
        public void removeLayoutComponent(Component comp) {
          
        }

        @Override
        public Dimension preferredLayoutSize(Container parent) {
             synchronized (parent.getTreeLock()) {
                return new Dimension(0, 0);
                
            }
        }
        

        @Override
        public Dimension minimumLayoutSize(Container parent) {
             synchronized (parent.getTreeLock()) {
                return new Dimension(0, 0);
            }
        }

        @Override
        public void layoutContainer(Container parent) {
            synchronized (parent.getTreeLock()) {
                int width = parent.getWidth();
                int height = parent.getHeight();
                int loginWidth = UIScale.scale(420);
                int loginHeight = pnLogin.getPreferredSize().height;
                int x = (width - loginWidth) / 2;
                int y = (height - loginHeight) / 2;
                pnLogin.setBounds(x, y, loginWidth, loginHeight);
            }
        }
        
    }
    private class LoginLayout implements LayoutManager {
        private final int titleGap = 10;
        private final int textGap = 10;
        private final int labelGab = 10;
        private final int buttonGap = 10;
        
        @Override
        public void addLayoutComponent(String name, Component comp) {
           
        }

        @Override
        public void removeLayoutComponent(Component comp) {
           
        }

        @Override
        public Dimension preferredLayoutSize(Container parent) {
            synchronized (parent.getTreeLock()) {
        Insets insets = parent.getInsets();
        int height = insets.top + insets.bottom;

        height += lb_logo.getPreferredSize().height;
        height += UIScale.scale(titleGap);
        height += lb_title.getPreferredSize().height;
        height += UIScale.scale(titleGap);
        height += lb_user.getPreferredSize().height;
        height += UIScale.scale(labelGab);
        height += txt_username.getPreferredSize().height;
        height += UIScale.scale(textGap);

        height += lb_pass.getPreferredSize().height;
        height += UIScale.scale(labelGab);
        height += txt_pass.getPreferredSize().height;
        height += UIScale.scale(buttonGap);
        height += btn_login.getPreferredSize().height;
        height += UIScale.scale(buttonGap);
        height += btn_register.getPreferredSize().height;

        return new Dimension(0, height);
    }
        }

        @Override
        public Dimension minimumLayoutSize(Container parent) {
             synchronized (parent.getTreeLock()) {
                return new Dimension(0, 0);
            }
        }

        @Override
        public void layoutContainer(Container parent) {
             synchronized (parent.getTreeLock()) {
        Insets insets = parent.getInsets();
        int x = insets.left;
        int y = insets.top;
        int width = parent.getWidth() - (insets.left + insets.right);

        lb_logo.setBounds(x, y, width, lb_logo.getPreferredSize().height);
        y += lb_logo.getPreferredSize().height + UIScale.scale(titleGap);

        lb_title.setBounds(x, y, width, lb_title.getPreferredSize().height);
        y += lb_title.getPreferredSize().height + UIScale.scale(titleGap);

        lb_user.setBounds(x, y, width, lb_user.getPreferredSize().height);
        y += lb_user.getPreferredSize().height + UIScale.scale(labelGab);

        txt_username.setBounds(x, y, width, txt_username.getPreferredSize().height);
        y += txt_username.getPreferredSize().height + UIScale.scale(textGap);

        lb_pass.setBounds(x, y, width, lb_pass.getPreferredSize().height);
        y += lb_pass.getPreferredSize().height + UIScale.scale(labelGab);

        txt_pass.setBounds(x, y, width, txt_pass.getPreferredSize().height);
        y += txt_pass.getPreferredSize().height + UIScale.scale(buttonGap);

        btn_login.setBounds(x, y, width, btn_login.getPreferredSize().height);
        btn_register.setBounds(x, y, width, btn_register.getPreferredSize().height);
    }
        }
        
    }
}

