/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.form;

import com.app.config.koneksi;
import static com.app.form.FormLogin.userID;
import static com.app.form.FormLogin.userLevel;
import static com.app.form.FormLogin.userName;
import com.app.main.FormMenuUtama;
import com.formdev.flatlaf.FlatClientProperties;
import com.mysql.jdbc.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author LENOVO
 */
public class FormRFID extends javax.swing.JPanel {
    public final Connection conn =  koneksi.getKoneksi();
    public static String userID;
    public static String userName;
    public static String userLevel;

    /**
     * Creates new form FormRFID
     */
    
    public FormRFID() {
        initComponents();
  
        setLayoutForm();
       
        
    }
    
    private void setLayoutForm () {
       txt_id.putClientProperty(FlatClientProperties.STYLE, "arc:20;");
       txt_id.putClientProperty("JTextField.placeholderText", "Tempelkan Kartu Anda");
    }
    
    private boolean checkLoginWithRFID(String id) {
    try {
        Connection conn = Koneksi.getConnection();
        String sql = "SELECT * FROM tb_user WHERE id = ?";
        PreparedStatement ps = (PreparedStatement) conn.prepareStatement(sql);
        ps.setString(1, id);
        ResultSet rs = ps.executeQuery();
        
        if (rs.next()) {
            // Gunakan nama kelas.variabel untuk mengakses static variable
         FormRFID.userID = rs.getString("id");
         FormRFID.userName = rs.getString("nama");
         FormRFID.userLevel = rs.getString("level");
            
            System.out.println("Debug - UserLevel: " + FormRFID.userLevel); // Untuk debugging
            
            JOptionPane.showMessageDialog(this, 
                "Selamat datang, " + userName + "!\nAnda login sebagai " + userLevel, 
                "Login Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
            
            rs.close();
            ps.close();
            return true;
        }
        
        rs.close();
        ps.close();
    } catch (SQLException e) {
        e.printStackTrace();
    }
    return false;
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_id = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 140, 30));

        jButton1.setBackground(new java.awt.Color(125, 99, 41));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/icon/Kembali.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 301, 40, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/icon/LOGIN_RFID_resized.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FormMenuUtama.logout();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
         String userID = txt_id.getText();
        
        // Validasi input
        if (userID.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Silahkan Tempelkan Kartu Anda", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Cek login ke database dengan ID
        if (checkLoginWithRFID(userID)) {
            // Reset field setelah login berhasil
            txt_id.setText("");
            
            // Arahkan ke menu utama sesuai level
            FormMenuUtama.showMainMenu();
        } else {
            JOptionPane.showMessageDialog(this, 
                "ID User tidak valid atau belum terdaftar", 
                "Login Gagal", 
                JOptionPane.ERROR_MESSAGE);
        }
    
    }//GEN-LAST:event_txt_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables
}
