/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.app.form;

import com.app.config.koneksi;
import static com.app.form.Koneksi.getConnection;
import com.app.main.FormMenuUtama;
import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.util.UIScale;
import com.mysql.jdbc.PreparedStatement;
import java.awt.Color;

import java.awt.image.BufferedImage;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;



/**
 *
 * @author LENOVO
 */
public class FormLogin extends javax.swing.JPanel {
    public final Connection conn =  koneksi.getKoneksi();
    public static String userID;
    public static String userName;
    public static String userLevel;
  
    private BufferedImage backgroundImage;

    /**
     * Creates new form FormLogin
     */
    public FormLogin() {
        
        initComponents();
        setLayoutForm();
        txt_username.requestFocus();
       
        
    }
    private boolean checkLogin(String username, String password) {
    try {
        // Dapatkan koneksi database
        Connection conn = Koneksi.getConnection();
        
        // Query untuk memeriksa login menggunakan PreparedStatement
        String sql = "SELECT * FROM tb_user WHERE username = ? AND password = ?";
        PreparedStatement ps = (PreparedStatement) conn.prepareStatement(sql);
        ps.setString(1, username);
        ps.setString(2, password);
        
        // Eksekusi query dengan PreparedStatement, bukan Statement
        ResultSet rs = ps.executeQuery();
        
        // Jika data ditemukan (login berhasil)
        if (rs.next()) {
            // Simpan data user yang login
          userID = rs.getString("id");
          userName = rs.getString("nama");
          userLevel = rs.getString("level");
            
            JOptionPane.showMessageDialog(this, 
                "Selamat datang, " + userName + "!\nAnda login sebagai " + userLevel, 
                "Login Berhasil", 
                JOptionPane.INFORMATION_MESSAGE);
            
            // Tutup resources
            rs.close();
            ps.close();
            
            return true;
        }
        
        // Tutup resources
        rs.close();
        ps.close();
        
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, 
            "Error: " + e.getMessage(), 
            "Database Error", 
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    
    return false;
}
    
    
    
    private void setLayoutForm () {
       txt_username.putClientProperty(FlatClientProperties.STYLE, "arc:20;");
       txt_username.putClientProperty("JTextField.placeholderText", "Masukkan username Anda");
        txt_pass.putClientProperty(FlatClientProperties.STYLE, ""
        + "arc:20;"
        + "showRevealButton:true;"
        + "showCapsLock:true;");
        txt_pass.putClientProperty("JTextField.placeholderText", "Masukkan password Anda");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_register = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_register.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        lbl_register.setForeground(new java.awt.Color(0, 0, 0));
        lbl_register.setText("Register");
        lbl_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_registerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_registerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_registerMouseExited(evt);
            }
        });
        jPanel1.add(lbl_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 60, 40));

        btn_login.setBackground(new java.awt.Color(177, 131, 40));
        btn_login.setForeground(new java.awt.Color(255, 255, 255));
        btn_login.setText("Login");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel1.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 170, 30));

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 250, 30));

        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 250, 30));

        jButton2.setBackground(new java.awt.Color(177, 131, 40));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("RFID");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/app/icon/LOGIN_app_resized_750x512.png"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // Dapatkan nilai dari input fields
        String username = txt_username.getText();
        String password = new String(txt_pass.getPassword());
        
        // Validasi input
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                "Username dan Password tidak boleh kosong", 
                "Peringatan", 
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Cek login ke database
        if (checkLogin(username, password)) {
            // Reset field setelah login berhasil
            txt_username.setText("");
            txt_pass.setText("");
            
            // Arahkan ke menu utama sesuai level
            FormMenuUtama.showMainMenu();
        } else {
            JOptionPane.showMessageDialog(this, 
                "Username atau Password salah", 
                "Login Gagal", 
                JOptionPane.ERROR_MESSAGE);
        }
    
 
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FormMenuUtama.goTorfid();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void lbl_registerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseEntered
        // TODO add your handling code here:
          lbl_register.setForeground(Color.blue);
    }//GEN-LAST:event_lbl_registerMouseEntered

    private void lbl_registerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseExited
        // TODO add your handling code here:
        lbl_register.setForeground(Color.black);
    }//GEN-LAST:event_lbl_registerMouseExited

    private void lbl_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_registerMouseClicked
        // TODO add your handling code here:
         FormMenuUtama.goToRegister();
      
    }//GEN-LAST:event_lbl_registerMouseClicked

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
        btn_loginActionPerformed(evt);
    }//GEN-LAST:event_txt_passActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_login;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_register;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

  
}
