/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.app.main;


import com.app.form.FormLogin;
import com.app.form.FormRFID;
import com.app.form.FormRegister;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.extras.FlatAnimatedLafChange;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;



/**
 *
 * @author LENOVO
 */
public class FormMenuUtama extends javax.swing.JFrame {
    private static FormMenuUtama app;
    private final CardLayout cardLayout = new CardLayout();
    private final JPanel container = new JPanel(cardLayout);
    private final FormLogin loginPanel;
    private final FormRegister registerPanel;
    private final FormRFID RFIDPanel;
    private Main mainPanel;

    
    
  public FormMenuUtama() {
        initComponents();
        setSize(766, 549);
        setLocationRelativeTo(null);
        // Inisialisasi panel
        loginPanel = new FormLogin();
        registerPanel = new FormRegister();
        RFIDPanel = new FormRFID();
        mainPanel = new Main(); // Initial main panel (will be recreated on login)
        
        // Tambah panel ke CardLayout
        container.add(loginPanel, "login");
        container.add(registerPanel, "register");
        container.add(RFIDPanel, "rfid");
        container.add(mainPanel, "main");
        // Set kontainer utama
        setContentPane(container);
        cardLayout.show(container, "login");

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
    public static void main(String args[]) {
        FlatLaf.registerCustomDefaultsSource("com.app.theme");
        FlatLightLaf.setup();
        
        java.awt.EventQueue.invokeLater(() -> {
            app = new FormMenuUtama();
            app.setVisible(true);
        });
         
    }
    
     public static void showMainMenu() {
        FlatAnimatedLafChange.showSnapshot();
        
        // Recreate the Main panel to initialize with the correct user level
        app.container.remove(app.mainPanel);
        app.mainPanel = new Main(); // This will now use FormLogin.userLevel
        app.container.add(app.mainPanel, "main");
        
        app.cardLayout.show(app.container, "main");
        setSelectedMenu(0, 0);
        app.mainPanel.applyComponentOrientation(app.getComponentOrientation());
        app.mainPanel.hideMenu();
        SwingUtilities.updateComponentTreeUI(app.mainPanel);
        FlatAnimatedLafChange.hideSnapshotWithAnimation();
        
    }
    public static void logout() {
        FlatAnimatedLafChange.showSnapshot();
        app.cardLayout.show(app.container, "login");
        app.loginPanel.applyComponentOrientation(app.getComponentOrientation());
        SwingUtilities.updateComponentTreeUI(app.loginPanel);
        FlatAnimatedLafChange.hideSnapshotWithAnimation();
    }

    public static void goToRegister() {
        app.cardLayout.show(app.container, "register");
    }
    
      public static void goTorfid() {
        app.cardLayout.show(app.container, "rfid");
         SwingUtilities.invokeLater(() -> {
        app.RFIDPanel.txt_id.requestFocusInWindow(); // Pastikan txt_id public atau pakai getter
    });
    }

    public static void setSelectedMenu(int index, int subMenu) {
        app.mainPanel.setSelectedMenu(index, subMenu);
    }

    public static void showForm(Component component) {
        component.applyComponentOrientation(app.getComponentOrientation());
        app.mainPanel.showForm(component);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
